# Site Info
title: Codinfox Lanyon
tagline: 'A Jekyll theme based on Lanyon'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: "/liuzhiyue.github.io/"
url: https://yuppiesyue.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: dennis
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/feed/
    github:    https://github.com/codinfox
    # facebook:  <hide>
    twitter:
    weibo:     https://weibo.com/u/1272340123/home?wvr=5
    email:     15810691519@163.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/index.jpg
  caption: Photo In &copy; <a href="https://www.myswitzerland.com/zh-hans/destinations/wengen/">Wengen | Switzerland</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-15810691519' # leave blank if you don't want google analytics
disqus_short_name: 'yuppies_yue' # leave blank if you don't want disqus

