# Site Info
title: Yuppies Yue
tagline: 'Believe in yourself'
description: 'A Jekyll theme adapted from <a href="" target="_blank">Dennis</a>. Made by <a href="https://github.com/YuppiesYue" target="_blank">@Dennis</a>.'
baseurl: "/liuzhiyue.github.io/"
url: https://yuppiesyue.github.io/
logo: '/public/logo.png'
gravatar: '/public/img/head_top3.jpg'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: dennis
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/feed/
    github:    https://github.com/YuppiesYue
    # facebook:  <hide>
    twitter:
    weibo:     https://weibo.com/u/1272340123/home?wvr=5
    email:     15810691519@163.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/YuppiesYue/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/index20191123.jpg
  caption: Photo In &copy; <a href="https://baike.baidu.com/item/%E8%92%82%E7%BD%97%E5%B0%94%E5%B7%9E/2402748?fr=aladdin&fromtitle=%E5%9B%A0%E6%96%AF%E5%B8%83%E9%B2%81%E5%85%8B&fromid=1783869">Innsbruck | Austria</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-15810691519' # leave blank if you don't want google analytics
disqus_short_name: 'yuppies_yue' # leave blank if you don't want disqus

